// Code generated by protoc-gen-go. DO NOT EDIT.
// source: function-service.proto

package ppfunction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CallDeviceFunctionRequest struct {
	DeviceEUI            string   `protobuf:"bytes,1,opt,name=deviceEUI,proto3" json:"deviceEUI,omitempty"`
	FunctionName         string   `protobuf:"bytes,2,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Param1               string   `protobuf:"bytes,3,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               string   `protobuf:"bytes,4,opt,name=param2,proto3" json:"param2,omitempty"`
	Param3               string   `protobuf:"bytes,5,opt,name=param3,proto3" json:"param3,omitempty"`
	Param4               string   `protobuf:"bytes,6,opt,name=param4,proto3" json:"param4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallDeviceFunctionRequest) Reset()         { *m = CallDeviceFunctionRequest{} }
func (m *CallDeviceFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*CallDeviceFunctionRequest) ProtoMessage()    {}
func (*CallDeviceFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca858f07ad120e5, []int{0}
}

func (m *CallDeviceFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallDeviceFunctionRequest.Unmarshal(m, b)
}
func (m *CallDeviceFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallDeviceFunctionRequest.Marshal(b, m, deterministic)
}
func (m *CallDeviceFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallDeviceFunctionRequest.Merge(m, src)
}
func (m *CallDeviceFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_CallDeviceFunctionRequest.Size(m)
}
func (m *CallDeviceFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallDeviceFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallDeviceFunctionRequest proto.InternalMessageInfo

func (m *CallDeviceFunctionRequest) GetDeviceEUI() string {
	if m != nil {
		return m.DeviceEUI
	}
	return ""
}

func (m *CallDeviceFunctionRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *CallDeviceFunctionRequest) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

func (m *CallDeviceFunctionRequest) GetParam2() string {
	if m != nil {
		return m.Param2
	}
	return ""
}

func (m *CallDeviceFunctionRequest) GetParam3() string {
	if m != nil {
		return m.Param3
	}
	return ""
}

func (m *CallDeviceFunctionRequest) GetParam4() string {
	if m != nil {
		return m.Param4
	}
	return ""
}

type GetDeviceFunctionsRequest struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceFunctionsRequest) Reset()         { *m = GetDeviceFunctionsRequest{} }
func (m *GetDeviceFunctionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceFunctionsRequest) ProtoMessage()    {}
func (*GetDeviceFunctionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca858f07ad120e5, []int{1}
}

func (m *GetDeviceFunctionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceFunctionsRequest.Unmarshal(m, b)
}
func (m *GetDeviceFunctionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceFunctionsRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceFunctionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceFunctionsRequest.Merge(m, src)
}
func (m *GetDeviceFunctionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceFunctionsRequest.Size(m)
}
func (m *GetDeviceFunctionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceFunctionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceFunctionsRequest proto.InternalMessageInfo

func (m *GetDeviceFunctionsRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DeviceFunctions struct {
	Functions            []*DeviceFunction `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeviceFunctions) Reset()         { *m = DeviceFunctions{} }
func (m *DeviceFunctions) String() string { return proto.CompactTextString(m) }
func (*DeviceFunctions) ProtoMessage()    {}
func (*DeviceFunctions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca858f07ad120e5, []int{2}
}

func (m *DeviceFunctions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceFunctions.Unmarshal(m, b)
}
func (m *DeviceFunctions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceFunctions.Marshal(b, m, deterministic)
}
func (m *DeviceFunctions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceFunctions.Merge(m, src)
}
func (m *DeviceFunctions) XXX_Size() int {
	return xxx_messageInfo_DeviceFunctions.Size(m)
}
func (m *DeviceFunctions) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceFunctions.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceFunctions proto.InternalMessageInfo

func (m *DeviceFunctions) GetFunctions() []*DeviceFunction {
	if m != nil {
		return m.Functions
	}
	return nil
}

type DeviceFunction struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Param1Type           string   `protobuf:"bytes,3,opt,name=param1type,proto3" json:"param1type,omitempty"`
	Param2Type           string   `protobuf:"bytes,4,opt,name=param2type,proto3" json:"param2type,omitempty"`
	Param3Type           string   `protobuf:"bytes,5,opt,name=param3type,proto3" json:"param3type,omitempty"`
	Param4Type           string   `protobuf:"bytes,6,opt,name=param4type,proto3" json:"param4type,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Param1Description    string   `protobuf:"bytes,8,opt,name=param1description,proto3" json:"param1description,omitempty"`
	Param2Description    string   `protobuf:"bytes,9,opt,name=param2description,proto3" json:"param2description,omitempty"`
	Param3Description    string   `protobuf:"bytes,10,opt,name=param3description,proto3" json:"param3description,omitempty"`
	Param4Description    string   `protobuf:"bytes,11,opt,name=param4description,proto3" json:"param4description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceFunction) Reset()         { *m = DeviceFunction{} }
func (m *DeviceFunction) String() string { return proto.CompactTextString(m) }
func (*DeviceFunction) ProtoMessage()    {}
func (*DeviceFunction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca858f07ad120e5, []int{3}
}

func (m *DeviceFunction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceFunction.Unmarshal(m, b)
}
func (m *DeviceFunction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceFunction.Marshal(b, m, deterministic)
}
func (m *DeviceFunction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceFunction.Merge(m, src)
}
func (m *DeviceFunction) XXX_Size() int {
	return xxx_messageInfo_DeviceFunction.Size(m)
}
func (m *DeviceFunction) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceFunction.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceFunction proto.InternalMessageInfo

func (m *DeviceFunction) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *DeviceFunction) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DeviceFunction) GetParam1Type() string {
	if m != nil {
		return m.Param1Type
	}
	return ""
}

func (m *DeviceFunction) GetParam2Type() string {
	if m != nil {
		return m.Param2Type
	}
	return ""
}

func (m *DeviceFunction) GetParam3Type() string {
	if m != nil {
		return m.Param3Type
	}
	return ""
}

func (m *DeviceFunction) GetParam4Type() string {
	if m != nil {
		return m.Param4Type
	}
	return ""
}

func (m *DeviceFunction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeviceFunction) GetParam1Description() string {
	if m != nil {
		return m.Param1Description
	}
	return ""
}

func (m *DeviceFunction) GetParam2Description() string {
	if m != nil {
		return m.Param2Description
	}
	return ""
}

func (m *DeviceFunction) GetParam3Description() string {
	if m != nil {
		return m.Param3Description
	}
	return ""
}

func (m *DeviceFunction) GetParam4Description() string {
	if m != nil {
		return m.Param4Description
	}
	return ""
}

type Response struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ca858f07ad120e5, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*CallDeviceFunctionRequest)(nil), "ppfunction.CallDeviceFunctionRequest")
	proto.RegisterType((*GetDeviceFunctionsRequest)(nil), "ppfunction.GetDeviceFunctionsRequest")
	proto.RegisterType((*DeviceFunctions)(nil), "ppfunction.DeviceFunctions")
	proto.RegisterType((*DeviceFunction)(nil), "ppfunction.DeviceFunction")
	proto.RegisterType((*Response)(nil), "ppfunction.Response")
}

func init() { proto.RegisterFile("function-service.proto", fileDescriptor_6ca858f07ad120e5) }

var fileDescriptor_6ca858f07ad120e5 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcb, 0x6a, 0xe3, 0x30,
	0x14, 0x86, 0xe3, 0x49, 0xec, 0x89, 0x4f, 0x86, 0x19, 0x46, 0x64, 0x82, 0x92, 0x29, 0xc5, 0x08,
	0x0a, 0x59, 0xb4, 0x81, 0xca, 0x5e, 0x14, 0xba, 0xec, 0x8d, 0x52, 0xe8, 0xc2, 0xa1, 0x9b, 0xee,
	0xdc, 0x58, 0x01, 0x43, 0x62, 0xab, 0x96, 0x53, 0x9a, 0xf7, 0xe9, 0x6b, 0x74, 0xdf, 0xc7, 0x2a,
	0x91, 0x2f, 0x39, 0x8e, 0x93, 0xa5, 0xfe, 0xef, 0xb3, 0x39, 0xfc, 0xd2, 0x81, 0xc1, 0x7c, 0x15,
	0xcf, 0xb2, 0x28, 0x89, 0xcf, 0x94, 0x48, 0xdf, 0xa2, 0x99, 0x98, 0xc8, 0x34, 0xc9, 0x12, 0x02,
	0x52, 0x96, 0x84, 0x7d, 0x1a, 0x30, 0xbc, 0x0a, 0x16, 0x8b, 0x6b, 0xb1, 0x11, 0x6e, 0x8b, 0xd8,
	0x17, 0xaf, 0x2b, 0xa1, 0x32, 0x72, 0x04, 0x76, 0xa8, 0xc1, 0xcd, 0xd3, 0x3d, 0x35, 0x1c, 0x63,
	0x6c, 0xfb, 0xdb, 0x80, 0x30, 0xf8, 0x55, 0xfe, 0xe7, 0x31, 0x58, 0x0a, 0xfa, 0x43, 0x0b, 0xb5,
	0x8c, 0x0c, 0xc0, 0x92, 0x41, 0x1a, 0x2c, 0xcf, 0x69, 0x5b, 0xd3, 0xe2, 0x54, 0xe5, 0x9c, 0x76,
	0x50, 0xce, 0xab, 0xdc, 0xa5, 0x26, 0xca, 0xdd, 0x2a, 0xf7, 0xa8, 0x85, 0x72, 0x8f, 0x5d, 0xc2,
	0xf0, 0x4e, 0x64, 0xf5, 0xe9, 0x55, 0x39, 0xfe, 0x31, 0x40, 0x14, 0x8a, 0x38, 0x8b, 0xe6, 0x91,
	0x48, 0x8b, 0xf9, 0x51, 0xc2, 0x1e, 0xe0, 0xcf, 0xce, 0x97, 0xe4, 0x02, 0xec, 0x72, 0x7e, 0x45,
	0x0d, 0xa7, 0x3d, 0xee, 0xf1, 0xd1, 0x64, 0xdb, 0xd7, 0x64, 0xa7, 0xa7, 0xad, 0xcc, 0x3e, 0xda,
	0xf0, 0xbb, 0x4e, 0x1b, 0x05, 0x19, 0x7b, 0x0a, 0xea, 0x83, 0x19, 0xc5, 0xa1, 0x78, 0xd7, 0xed,
	0x99, 0x7e, 0x7e, 0xd8, 0x4c, 0x9e, 0x17, 0x95, 0xad, 0xa5, 0x28, 0xaa, 0x43, 0x49, 0xc5, 0xb9,
	0xe6, 0x1d, 0xc4, 0x79, 0x8d, 0xbb, 0x9a, 0x9b, 0x88, 0xbb, 0x35, 0xee, 0x69, 0x6e, 0x21, 0xae,
	0x13, 0xe2, 0x40, 0x2f, 0x14, 0x6a, 0x96, 0x46, 0x72, 0x33, 0x28, 0xfd, 0xa9, 0x05, 0x1c, 0x91,
	0x53, 0xf8, 0x9b, 0xcf, 0x83, 0xbd, 0xae, 0xf6, 0x9a, 0xa0, 0xb2, 0x39, 0xb6, 0x6d, 0x64, 0xf3,
	0x7d, 0xb6, 0x8b, 0x6d, 0x40, 0xb6, 0xbb, 0xcf, 0xf6, 0xb0, 0xdd, 0x43, 0x36, 0x06, 0xcc, 0x81,
	0xae, 0x2f, 0x94, 0x4c, 0x62, 0xa5, 0xbb, 0x4f, 0x85, 0x5c, 0xac, 0x8b, 0x8b, 0xc9, 0x0f, 0xfc,
	0xcb, 0x80, 0x7f, 0xf5, 0x8b, 0x9c, 0xe6, 0xeb, 0x43, 0xa6, 0x40, 0x9a, 0xbb, 0x42, 0x4e, 0xf0,
	0xfb, 0x38, 0xb8, 0x4b, 0xa3, 0x3e, 0xd6, 0xca, 0x11, 0x58, 0x8b, 0x3c, 0x03, 0x69, 0xbe, 0xe0,
	0xfa, 0x4f, 0x0f, 0xbe, 0xf0, 0xd1, 0xff, 0xc3, 0x6f, 0x53, 0xb1, 0xd6, 0x8b, 0xa5, 0x17, 0xde,
	0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x07, 0x20, 0x5e, 0x0a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceFunctionServiceClient is the client API for DeviceFunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceFunctionServiceClient interface {
	CallDeviceFunction(ctx context.Context, in *CallDeviceFunctionRequest, opts ...grpc.CallOption) (*Response, error)
	GetDeviceFunctions(ctx context.Context, in *GetDeviceFunctionsRequest, opts ...grpc.CallOption) (*DeviceFunctions, error)
}

type deviceFunctionServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceFunctionServiceClient(cc *grpc.ClientConn) DeviceFunctionServiceClient {
	return &deviceFunctionServiceClient{cc}
}

func (c *deviceFunctionServiceClient) CallDeviceFunction(ctx context.Context, in *CallDeviceFunctionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/ppfunction.DeviceFunctionService/CallDeviceFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceFunctionServiceClient) GetDeviceFunctions(ctx context.Context, in *GetDeviceFunctionsRequest, opts ...grpc.CallOption) (*DeviceFunctions, error) {
	out := new(DeviceFunctions)
	err := c.cc.Invoke(ctx, "/ppfunction.DeviceFunctionService/GetDeviceFunctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceFunctionServiceServer is the server API for DeviceFunctionService service.
type DeviceFunctionServiceServer interface {
	CallDeviceFunction(context.Context, *CallDeviceFunctionRequest) (*Response, error)
	GetDeviceFunctions(context.Context, *GetDeviceFunctionsRequest) (*DeviceFunctions, error)
}

// UnimplementedDeviceFunctionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceFunctionServiceServer struct {
}

func (*UnimplementedDeviceFunctionServiceServer) CallDeviceFunction(ctx context.Context, req *CallDeviceFunctionRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallDeviceFunction not implemented")
}
func (*UnimplementedDeviceFunctionServiceServer) GetDeviceFunctions(ctx context.Context, req *GetDeviceFunctionsRequest) (*DeviceFunctions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceFunctions not implemented")
}

func RegisterDeviceFunctionServiceServer(s *grpc.Server, srv DeviceFunctionServiceServer) {
	s.RegisterService(&_DeviceFunctionService_serviceDesc, srv)
}

func _DeviceFunctionService_CallDeviceFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallDeviceFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceFunctionServiceServer).CallDeviceFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppfunction.DeviceFunctionService/CallDeviceFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceFunctionServiceServer).CallDeviceFunction(ctx, req.(*CallDeviceFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceFunctionService_GetDeviceFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceFunctionServiceServer).GetDeviceFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ppfunction.DeviceFunctionService/GetDeviceFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceFunctionServiceServer).GetDeviceFunctions(ctx, req.(*GetDeviceFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceFunctionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ppfunction.DeviceFunctionService",
	HandlerType: (*DeviceFunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallDeviceFunction",
			Handler:    _DeviceFunctionService_CallDeviceFunction_Handler,
		},
		{
			MethodName: "GetDeviceFunctions",
			Handler:    _DeviceFunctionService_GetDeviceFunctions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "function-service.proto",
}
