# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='function-service.proto',
  package='ppfunction',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x66unction-service.proto\x12\nppfunction\"\x84\x01\n\x19\x43\x61llDeviceFunctionRequest\x12\x11\n\tdeviceEUI\x18\x01 \x01(\t\x12\x14\n\x0c\x66unctionName\x18\x02 \x01(\t\x12\x0e\n\x06param1\x18\x03 \x01(\t\x12\x0e\n\x06param2\x18\x04 \x01(\t\x12\x0e\n\x06param3\x18\x05 \x01(\t\x12\x0e\n\x06param4\x18\x06 \x01(\t\"/\n\x19GetDeviceFunctionsRequest\x12\x12\n\nidentifier\x18\x01 \x01(\t\"@\n\x0f\x44\x65viceFunctions\x12-\n\tfunctions\x18\x01 \x03(\x0b\x32\x1a.ppfunction.DeviceFunction\"\x86\x02\n\x0e\x44\x65viceFunction\x12\x14\n\x0c\x66unctionName\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x12\n\nparam1type\x18\x03 \x01(\t\x12\x12\n\nparam2type\x18\x04 \x01(\t\x12\x12\n\nparam3type\x18\x05 \x01(\t\x12\x12\n\nparam4type\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x19\n\x11param1description\x18\x08 \x01(\t\x12\x19\n\x11param2description\x18\t \x01(\t\x12\x19\n\x11param3description\x18\n \x01(\t\x12\x19\n\x11param4description\x18\x0b \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t2\xc8\x01\n\x15\x44\x65viceFunctionService\x12S\n\x12\x43\x61llDeviceFunction\x12%.ppfunction.CallDeviceFunctionRequest\x1a\x14.ppfunction.Response\"\x00\x12Z\n\x12GetDeviceFunctions\x12%.ppfunction.GetDeviceFunctionsRequest\x1a\x1b.ppfunction.DeviceFunctions\"\x00\x62\x06proto3')
)




_CALLDEVICEFUNCTIONREQUEST = _descriptor.Descriptor(
  name='CallDeviceFunctionRequest',
  full_name='ppfunction.CallDeviceFunctionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceEUI', full_name='ppfunction.CallDeviceFunctionRequest.deviceEUI', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='functionName', full_name='ppfunction.CallDeviceFunctionRequest.functionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param1', full_name='ppfunction.CallDeviceFunctionRequest.param1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param2', full_name='ppfunction.CallDeviceFunctionRequest.param2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param3', full_name='ppfunction.CallDeviceFunctionRequest.param3', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param4', full_name='ppfunction.CallDeviceFunctionRequest.param4', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=171,
)


_GETDEVICEFUNCTIONSREQUEST = _descriptor.Descriptor(
  name='GetDeviceFunctionsRequest',
  full_name='ppfunction.GetDeviceFunctionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='ppfunction.GetDeviceFunctionsRequest.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=220,
)


_DEVICEFUNCTIONS = _descriptor.Descriptor(
  name='DeviceFunctions',
  full_name='ppfunction.DeviceFunctions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='functions', full_name='ppfunction.DeviceFunctions.functions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=286,
)


_DEVICEFUNCTION = _descriptor.Descriptor(
  name='DeviceFunction',
  full_name='ppfunction.DeviceFunction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='functionName', full_name='ppfunction.DeviceFunction.functionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='ppfunction.DeviceFunction.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param1type', full_name='ppfunction.DeviceFunction.param1type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param2type', full_name='ppfunction.DeviceFunction.param2type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param3type', full_name='ppfunction.DeviceFunction.param3type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param4type', full_name='ppfunction.DeviceFunction.param4type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ppfunction.DeviceFunction.description', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param1description', full_name='ppfunction.DeviceFunction.param1description', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param2description', full_name='ppfunction.DeviceFunction.param2description', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param3description', full_name='ppfunction.DeviceFunction.param3description', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param4description', full_name='ppfunction.DeviceFunction.param4description', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=551,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='ppfunction.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='ppfunction.Response.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=578,
)

_DEVICEFUNCTIONS.fields_by_name['functions'].message_type = _DEVICEFUNCTION
DESCRIPTOR.message_types_by_name['CallDeviceFunctionRequest'] = _CALLDEVICEFUNCTIONREQUEST
DESCRIPTOR.message_types_by_name['GetDeviceFunctionsRequest'] = _GETDEVICEFUNCTIONSREQUEST
DESCRIPTOR.message_types_by_name['DeviceFunctions'] = _DEVICEFUNCTIONS
DESCRIPTOR.message_types_by_name['DeviceFunction'] = _DEVICEFUNCTION
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallDeviceFunctionRequest = _reflection.GeneratedProtocolMessageType('CallDeviceFunctionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLDEVICEFUNCTIONREQUEST,
  '__module__' : 'function_service_pb2'
  # @@protoc_insertion_point(class_scope:ppfunction.CallDeviceFunctionRequest)
  })
_sym_db.RegisterMessage(CallDeviceFunctionRequest)

GetDeviceFunctionsRequest = _reflection.GeneratedProtocolMessageType('GetDeviceFunctionsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDEVICEFUNCTIONSREQUEST,
  '__module__' : 'function_service_pb2'
  # @@protoc_insertion_point(class_scope:ppfunction.GetDeviceFunctionsRequest)
  })
_sym_db.RegisterMessage(GetDeviceFunctionsRequest)

DeviceFunctions = _reflection.GeneratedProtocolMessageType('DeviceFunctions', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEFUNCTIONS,
  '__module__' : 'function_service_pb2'
  # @@protoc_insertion_point(class_scope:ppfunction.DeviceFunctions)
  })
_sym_db.RegisterMessage(DeviceFunctions)

DeviceFunction = _reflection.GeneratedProtocolMessageType('DeviceFunction', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEFUNCTION,
  '__module__' : 'function_service_pb2'
  # @@protoc_insertion_point(class_scope:ppfunction.DeviceFunction)
  })
_sym_db.RegisterMessage(DeviceFunction)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'function_service_pb2'
  # @@protoc_insertion_point(class_scope:ppfunction.Response)
  })
_sym_db.RegisterMessage(Response)



_DEVICEFUNCTIONSERVICE = _descriptor.ServiceDescriptor(
  name='DeviceFunctionService',
  full_name='ppfunction.DeviceFunctionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=581,
  serialized_end=781,
  methods=[
  _descriptor.MethodDescriptor(
    name='CallDeviceFunction',
    full_name='ppfunction.DeviceFunctionService.CallDeviceFunction',
    index=0,
    containing_service=None,
    input_type=_CALLDEVICEFUNCTIONREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeviceFunctions',
    full_name='ppfunction.DeviceFunctionService.GetDeviceFunctions',
    index=1,
    containing_service=None,
    input_type=_GETDEVICEFUNCTIONSREQUEST,
    output_type=_DEVICEFUNCTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICEFUNCTIONSERVICE)

DESCRIPTOR.services_by_name['DeviceFunctionService'] = _DEVICEFUNCTIONSERVICE

# @@protoc_insertion_point(module_scope)
